name: Triage

on: [pull_request]

jobs:
  labels:
    name: Labeling
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/labeler@v5
        with:
          dot: true
